<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'felipedecampos\\laravelsoftarchive\\test\\models\\archivedmodel' => __DIR__ . '/Models/ArchivedModel.php',
                'illuminate\\database\\eloquent\\softarchives' => dirname(__DIR__) . '/src/Illuminate/Database/Eloquent/SoftArchives.php',
                'illuminate\database\eloquent\softarchivingscope' => dirname(__DIR__) . '/src/Illuminate/Database/Eloquent/SoftArchivingScope.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require_once $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd